### PR TITLE
Adds No-IP to Providers [resolves #116]

### LINKED ISSUE #116: No-IP now supports CAA
https://www.noip.com now supports CAA records for Managed DNS domains and Enhanced hostnames.

### PR DESCRIPTION
**Pull request by davidrjonas**

### CODE REVIEW

**Comment by AGWA** [comment]
Thanks. Does No-IP have any documentation about this? https://www.google.com/search?q=site%3A.noip.com+%22CAA%22 returns no results and http://www.noip.com/help.php suggests that the only supported record types are A, CNAME, TXT, SRV, and MX.

**Comment by davidrjonas** [comment]
It doesn't look like it. I'll see about getting docs updated to include CAA. Here is a screenshot of it in action, 
Screenshot_2019-07-25 My No-IP Managed DNS DNS CAA Record

**Comment by davidrjonas** [comment]
KB article added, https://www.noip.com/support/knowledgebase/adding-caa-records/

**Comment by AGWA** [comment]
Cherry-picked as b6894f96b99381f0397ebb1db6cc32619f4ade80. Thanks!

**Pull request closed without merging**
